### ISSUE TITLE
Java 11 testing

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#559] opened 2018-09-18 11:54 UTC
**While we only officially support Java 8**, we do some testing and provide some support for Java 11 (e.g. for JPMS module checks on 2.13). 

Please 👍 this ticket if this is important to you, to give us a sense of how to prioritize this. This is also a good spot to leave other feedback, or report an issue (for detailed reports, please open an individual ticket -- this one is more a "works for me / or not"). 

As always, for questions / higher-level discussions, please use [discourse](https://contributors.scala-lang.org).

  - [x] update https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html
  - [x] add jdk 11 to the travis CI matrix
  - [x] add jdk 11 to the community build matrix

**Comment by adriaanm** [comment] 2018-09-18 12:05
For a detailed list of features from JDK >= 9, see
  - [JDK 9+ features](https://github.com/scala/scala-dev/issues/139)
  - [JPMS module system](https://github.com/scala/scala-dev/issues/529)

**Comment by SethTisue** [comment] 2018-09-18 14:59
ticket on JDK 11 for the Scala community build: scala/community-builds#742.

(at the moment, the status is that I have run it on 11 locally, but we don't have a Jenkins job yet)

**Comment by m50d** [comment] 2018-09-19 07:32
Are you asking about JDK11 specifically or JDK9+ generally?

**Comment by adriaanm** [comment] 2018-09-19 07:35
To spend our (I mean the core team + all contributors) time efficiently in the face of Oracle's new 6-month cycle, I think our only realistic option is to test on LTS releases. We can discuss this as well, but I think it will be costly to track all intermediate ones.

**Comment by m50d** [comment] 2018-09-19 08:48
LTS-only sounds reasonable. From my selfish perspective I care that Scala gets tested on *some* 9+ version of the JDK (because I encounter issues that I believe are caused by 9's module changes), but it's not especially important to me whether that's 9, 10 or 11.

**Comment by markehammons** [comment] 2018-09-20 10:02
@adriaanm I will probably be jumping to the new releases on a regular basis since all my software works with java-11 at this point. Is it fine if I report any bugs I encounter related to changes in the intermediate releases?

**Comment by adriaanm** [comment] 2018-09-20 10:51
Sure, thank you! We appreciate the help in testing, and I don’t completely
rule out fixes for issues on intermediate updates, just setting
expectations.

**Comment by He-Pin** [comment] 2018-09-26 06:37
I think most people will jump directly to Java 11.

**Comment by da-liii** [comment] 2018-09-26 06:44
Java 9 or 10 is Windows Vista.

**Comment by weiwen99** [comment] 2018-09-26 07:02
We will upgrade to 11 from 8 as possible.

**Comment by kwinter** [comment] 2018-09-26 23:33
The inclusion and open-sourcing of Flight Recorder in JDK 11 gives a lot of reason to jump to it (I'm counting the days until we can)

**Comment by plokhotnyuk** [comment] 2018-09-27 07:01
IMHO most groundbreaking features of JDK 11 are:
- Graal compiler which is able to speed Scala code in run-time greatly
- ZGC which is enabler for usage of hardware scaled up with terabytes of RAM (especially for real-time services with huge in-memory caches and databases)

**Comment by xuwei-k** [comment] 2018-09-27 14:53
I have sent small pull requests.
- https://github.com/scala/scala/pull/7271
- https://github.com/scala/scala/pull/7273

**Comment by adriaanm** [comment] 2018-09-27 14:56
Thank you, @xuwei-k! PRs merged :-)

**Comment by xuwei-k** [comment] 2018-09-27 14:59
another failed tests with JDK11 (on my local)

- [ ] https://github.com/scala/scala/tree/0f926ac0988/test/files/run/reflection-fancy-java-classes
- [ ] https://github.com/scala/scala/tree/0f926ac0988/test/files/run/t6411a.scala
- [ ] https://github.com/scala/scala/tree/0f926ac0988/test/files/run/t6827.scala
- [ ] https://github.com/scala/scala/tree/0f926ac0988/test/files/run/t7455
- [x] https://github.com/scala/scala/tree/0f926ac0988/test/files/run/t9400.scala https://github.com/scala/scala/pull/7288

**Comment by eed3si9n** [comment] 2018-10-04 18:29
Got Travis CI to run JDK 11 testing for 2.12.x in https://github.com/scala/scala/pull/7311.

Here are some excerpts from https://travis-ci.org/scala/scala/jobs/437207406: 

```
# Failed test paths (this command will update checkfiles)
partest --update-check \
  /home/travis/build/scala/scala/test/files/run/classfile-format-52.scala \
  /home/travis/build/scala/scala/test/files/run/getClassTest-new.scala \
  /home/travis/build/scala/scala/test/files/run/getClassTest-old.scala \
  /home/travis/build/scala/scala/test/files/run/lambda-serialization-gc.scala \
  /home/travis/build/scala/scala/test/files/run/numbereq.scala \
  /home/travis/build/scala/scala/test/files/run/reflection-fancy-java-classes \
  /home/travis/build/scala/scala/test/files/run/t1167.scala \
  /home/travis/build/scala/scala/test/files/run/t2318.scala \
  /home/travis/build/scala/scala/test/files/run/t3425b \
  /home/travis/build/scala/scala/test/files/run/t4148.scala \
  /home/travis/build/scala/scala/test/files/run/t6411a.scala \
  /home/travis/build/scala/scala/test/files/run/t6669.scala \
  /home/travis/build/scala/scala/test/files/run/t6827.scala \
  /home/travis/build/scala/scala/test/files/run/t7455 \
  /home/travis/build/scala/scala/test/files/run/t7741a \
  /home/travis/build/scala/scala/test/files/run/t8549.scala \
  /home/travis/build/scala/scala/test/files/run/t9030.scala \
  /home/travis/build/scala/scala/test/files/run/t9437b.scala \
  /home/travis/build/scala/scala/test/files/run/t9529

[error] Failed: Total 1889, Failed 19, Errors 0, Passed 1870

# Failed test paths (this command will update checkfiles)
partest --update-check \
  /home/travis/build/scala/scala/test/files/neg/checksensible.scala \
  /home/travis/build/scala/scala/test/files/neg/t9529.scala \
  /home/travis/build/scala/scala/test/files/jvm/annotations.scala \
  /home/travis/build/scala/scala/test/files/jvm/javaReflection \
  /home/travis/build/scala/scala/test/files/jvm/t3003 \
  /home/travis/build/scala/scala/test/files/jvm/throws-annot.scala \
  /home/travis/build/scala/scala/test/files/jvm/value-class-in-jannotation.scala

[error] Failed: Total 2535, Failed 7, Errors 0, Passed 2528

[error] Failed: Total 1366, Failed 6, Errors 0, Passed 1355, Skipped 5
[error] Failed tests:
[error]  scala.tools.nsc.backend.jvm.opt.MethodLevelOptsTest
[error]  scala.reflect.ClassOfTest
[error]  scala.lang.annotations.RunTest
[error]  scala.tools.nsc.backend.jvm.opt.BoxUnboxTest
[info] Updating {file:/home/travis/build/scala/scala/}scalacheck...

[error] Failed: Total 4, Failed 4, Errors 0, Passed 0
[error] Failed tests:
[error]  tools.test.osgi.reflection.toolbox.ReflectionToolBoxTest
[error]  tools.test.osgi.BasicTest
[error]  tools.test.osgi.reflection.basic.BasicReflectionTest
[error]  tools.test.osgi.libonly.BasicLibraryTest

[error] 7 of 12 test tasks failed:
[error] - junit/test
[error]   - junit/test:test failed: sbt.TestsFailedException: Tests unsuccessful
[error] - scalacheck/test
[error]   - scalacheck/test:test failed: sbt.TestsFailedException: Tests unsuccessful
[error] - partest run
[error]   - test/it:testOnly failed: sbt.TestsFailedException: Tests unsuccessful
[error] - partest pos neg jvm
[error]   - test/it:testOnly failed: sbt.TestsFailedException: Tests unsuccessful
[error] - osgiTestFelix/test
[error] - osgiTestEclipse/test
[error] - library/mimaReportBinaryIssues
[error]   - library/mimaReportBinaryIssues failed: java.lang.RuntimeException: scala-library: Binary compatibility check failed!
```

Not sure how much of it is superficial failure due to test and how much is legitimate issue, but basically 99% of the test cases are passing.

**Comment by ijuma** [comment] 2018-10-28 15:38
Btw, ASM 7.0 is now out and it includes full non-experimental support for Java 11 and early support for Java 12.

**Comment by dbtsai** [comment] 2018-11-06 05:41
Hello, as majority of Spark users are still on Scala 2.11, do we have a plan to backport Java 11 work to Scala 2.11? Thanks!

**Comment by xuwei-k** [comment] 2018-11-06 06:03
> Btw, ASM 7.0 is now out and it includes full non-experimental support for Java 11 and early support for Java 12.

https://github.com/scala/scala/pull/7384

**Comment by adriaanm** [comment] 2018-11-06 07:48
Scala 2.11 is EOL, sorry. It came out 4.5 years ago and we provided updates for 3.5 years, until 2.12 had been out for a year. 

If someone is willing to sponsor the needed work (donating time ideally), we’re open to that.

**Comment by dbtsai** [comment] 2018-11-06 18:53
We'll discuss in Spark community, and see the possibility of moving to Scala 2.12 as default version in Spark 3.0. Thanks.

**Comment by JMLamodiere** [comment] 2019-01-02 17:14
Hello @adriaanm ! I cannot find the page listing the official End Of Life date of scala versions. For instance, I've found something about [2.11 EOL in the release not of 2.11.11](https://github.com/scala/scala/releases/tag/v2.11.11) , but cannot find the same information for 2.12 series. Could you please enlight me, and people in my situation ?
Thanks !

**Comment by adriaanm** [comment] 2019-01-07 13:34
Our OSS EOL policy is not set in stone (we do offer more precise terms in our commercial support). 

Generally, we try to maintain two versions prior to the current one in development, but it depends on our availability and that of community contributors, as well as the community's needs. Since our development cycle is between 18-24 months, this means we maintain a version for about 36 - 48 months after its initial .0 release.

**Comment by SethTisue** [comment] 2019-01-08 16:40
And more concretely, there will certainly be a 2.12.9 and it's likely there will be a few more 2.12.x releases after that, too, but with declining frequency.

2.12.5 and 2.12.7 had regressions that required prompt followup releases. if you leave those versions out, the pace recently has been:

* 2.12.8: December 2018
* 2.12.6: April 2018
* 2.12.4: October 2017

so unless a specific pressing need arises, expecting subsequent 2.12.x releases to each take 6 months or more is a reasonable expectation.

**Comment by cosmir17** [comment] 2019-05-01 22:26
Future Oracle Java 8 releases will be under a new license policy (commencing from 16th April 2019).   https://java.com/en/download/release_notice.jsp
It's not going to be free for production use.

Is this going to change a direction which version of JVM that Lightbend is going to be more supportive for Scala lib development? For example, this may be another reason for Java 11 support? could be for 9 as well (https://github.com/scala/scala-dev/issues/139)?
So far, Java 8 has been the primary platform.

**Comment by SethTisue** [comment] 2019-05-01 22:38
We expect that in OSS contexts everyone (including ourselves in the Scala org) will just use OpenJDK 8 instead of the Oracle one. It's fine.

When we test on 11, we are already doing it on OpenJDK, not Oracle's version.

re JDK 9, we aren't touching 9 or 10 anymore; see https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html

**Comment by cosmir17** [comment] 2019-05-01 22:48
I see. I originally came from Java background so I didn't know it's safe to use OpenJDK(to run scala code) in production.
Glad to know that Lightbend made a decision to support specific versions of JVMs rather than every version.

**Comment by toktarev** [comment] 2019-12-21 06:50
Tried to switch my project on java11.

I use xgboost (https://github.com/dmlc/xgboost) and scala inside, however
it failed with 

```
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: scala.Serializable
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]

```

Is this scala's bug or I need to add some configuration parameters for JVM args ?
i use scala 2.13.1

**Comment by toktarev** [comment] 2019-12-21 06:52
i use scala 2.13

**Comment by dwijnand** [comment] 2019-12-21 08:49
@toktarev Could you open an issue in https://github.com/scala/bug, please?  That way we can have a conversation around it, without overrunning this, more central, thread.

**Comment by toktarev** [comment] 2019-12-21 10:04
@dwijnand , yes sure:

https://github.com/scala/bug/issues/11832

**Comment by SethTisue** [comment] 2021-04-23 01:09
the last piece of this landed at https://github.com/scala/scala/pull/9579

**Closed as completed by SethTisue** 2021-04-23 01:09 UTC
Labels: t:java11, CI/publishing/infra
