### ISSUE TITLE
Release 2.11.13

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#451] opened 2017-11-28 22:29 UTC
**NOTE**: at this point, we are not committing to another 2.11 release -- this is a placeholder to collect TODOs in case we do decide to cut another release.

Motivation:
  - Backport ASM upgrade to fix regression: https://github.com/scala/scala/pull/6180
  - Fix regression in runner script with unset `$JAVA_HOME`
  - Opportunity for community to help with more targetted backports, in particular ones that help Spark along the lines of https://github.com/scala/scala/pull/6195
  - [ ] Backport https://github.com/scala/scala/pull/8210

**Comment by sjrd** [comment] 2017-11-28 22:33
Advertising a regression I had found in 2.10.7 and 2.11.12: https://github.com/scala/bug/issues/10609

Note that personally, I don't care whether it's going to be fixed or not; I just disabled the failing test in our test suite. But maybe this affects other people.

**Comment by mpetruska** [comment] 2017-11-29 16:29
Might make sense to talk about scala/scala#6195.
It causes a Spark-shell issue [SPARK-22393](https://issues.apache.org/jira/browse/SPARK-22393).
Please note that the changes in that PR are ["retrofitted"](https://github.com/apache/spark/pull/19846) into Spark-shell (not merged yet), so this is not really a priority.

**Comment by SethTisue** [comment] 2018-05-11 14:46
note that publishing 2.11.13 would now require either resurrecting some now-decayed/disabled Jenkins stuff, or backporting the Travis-CI-based publishing from 2.12.x

**Comment by smarter** [comment] 2018-07-02 00:31
Crashes due to -Yrangepos validation affect IDE and tooling (e.g. scalameta) users, so it'd make a ton of sense to backport https://github.com/scala/scala/pull/6754

**Comment by smarter** [comment] 2018-08-11 16:40
Apparently 2.12 can emit code that causes ambiguous method errors in javac starting with Java 11, this should be fixed by https://github.com/scala/scala/pull/7035. I assume that 2.11 is affected by this and could benefit from a backport.

**Comment by SethTisue** [comment] 2018-11-29 02:45
if this happens, we might want to backport the license change to Apache 2 (scala/scala#7314, scala/scala#7407, scala/scala#7730, scala/scala#8015)

**Comment by SethTisue** [comment] 2018-12-04 17:21
and undeprecate `.linesIterator`, as we did in 2.12.8

**Comment by SethTisue** [comment] 2019-01-24 02:26
and bump the copyright year to 2019 or whatever. (I'm about to PR this to 2.12.x.)

**Comment by SethTisue** [comment] 2019-01-24 18:16
this is only a would-be-nice, but if the 2.11.x REPL could be made to work on JDK 11, without risk of breaking something else, that'd be nice. it's https://github.com/scala/bug/issues/10603

**Comment by SethTisue** [comment] 2019-02-01 21:58
this hashmap fix backport PR could be reopened and merged: https://github.com/scala/scala/pull/7522

**Comment by SethTisue** [comment] 2019-03-13 14:29
> Backport ASM upgrade to fix regression: scala/scala#6180

and https://github.com/scala/scala/pull/7780

**Comment by adriaanm** [comment] 2019-05-24 15:00
The ASM 7 upgrade is trickier, but I have a PR for the 6.2 one (scala/scala#8079), which should be enough, as our ambitions for 2.11 don't extend beyond Java 11

**Comment by SethTisue** [comment] 2019-08-03 18:16
We should backport https://github.com/scala/scala/pull/8289 (fix Scaladoc generation on JDK 11+, as per https://github.com/scala/bug/issues/11635); I have seen it in the 2.11 community build (grizzled and monix both, in https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-jdk11-integrate-community-build/155/)

**Comment by SethTisue** [comment] 2019-08-08 02:33
~re: ASM upgrade, we should watch out for https://github.com/scala/bug/issues/11667 (unless that proves to be ASM 7 specific, and it sounds like we won't go all the way 7, recording it here regardless just in case)~ [edit: the bug is not related to the asm upgrade]

**Comment by SethTisue** [comment] 2019-08-16 17:06
note that we now require Java 8+ on the 2.11.x branch

**Comment by RussellSpitzer** [comment] 2020-02-26 18:39
We have seen scala/scala#8289 as well in some of our internal builds (as well as those using Spark)

**Comment by SethTisue** [comment] 2022-10-31 19:01
Closing, as this seems unlikely to ever happen, unless somebody threw money at us

**Closed as completed by SethTisue** 2022-10-31 19:01 UTC
