### ISSUE TITLE
sbt build: the `junit` project is not compiled with the compiler from source code

### ISSUE THREAD

**Issue by sjrd** [scala/scala-dev#136] opened 2016-04-22 11:28 UTC
It apparently simply uses the stock Scala compiler fetched from Maven. The ant build uses the compiler compiled from source to compile the JUnit tests (in `ant test.junit`).

This means that, when fixing an issue in the compiler, and using a JUnit test to test the fix, `sbt test` fails while `ant test.junit` succeeds.

**Comment by retronym** [comment] 2016-04-22 12:15
AFAICR, this was by design. Or rather, we realised that it would be hard to implement with our set of design principles for the SBT build (namely: bootstrapping was not something we wanted to handle internally in the build), and then convinced ourselves that this constraint was reasonable.

For tests of the new compiler, we either use partest, or, increasingly so, snippets of source code in strings in JUnit tests. The test case code itself should not rely on the latest compiler features.

**Comment by retronym** [comment] 2016-04-22 12:16
The previous incarnation of the SBT build did handle bootstrapping internally, but we found this led to non-functional problems in SBT (performance, memory leaks).

**Comment by sjrd** [comment] 2016-04-22 12:19
I understand why we do this to compile the standard library and the compiler. But it really seems weird that we don't use the freshly built compiler to compile the JUnit tests.

But well, if that's how it is, I yield ^^

**Comment by retronym** [comment] 2016-04-22 12:26
closing, but /cc @adriaanm to confirm my recollection

**Closed as completed by retronym** 2016-04-22 12:26 UTC
Labels: task

**Comment by lrytz** [comment] 2016-04-22 12:46
I agree this is an annoying problem, it keeps coming back often. your latest PR (https://github.com/scala/scala/pull/5117) is a good example: its test will fail for people using sbt until we push a new starr (right?). the same happens for people running the JUnit tests within IntelliJ.

**Comment by sjrd** [comment] 2016-04-22 12:51
Yes. That's why I used a partest instead of a JUnit test. `test/it:testOnly -- ./test/files/run/t9516.scala` passes from sbt, but `test` did not with a JUnit test.

**Comment by lrytz** [comment] 2016-04-22 12:54
oh, i overlooked that you did a partest test.

**Comment by adriaanm** [comment] 2016-04-22 18:34
On the bright side, this means we could more aggressively cache the compiled junit tests on the CI at some point :-)

It would still be good to have another project that uses junit to test the actual compiler, using the quick compiler to build the test sources. Not sure it's possible to switch ScalaInstances on a per-project basis, or maybe we should split out sbt build in two? One for building the compiler and one for building the tests using that compiler? The downside is that we diverge from common practice again then...
