### ISSUE TITLE
Spurious access error inheriting from a generic Java class with a protected constructor

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#345] opened 2017-03-25 12:10 UTC
```
⚡ tail sandbox/{Test.java,sub.scala} && printf "\n" && javac -d /tmp sandbox/Test.java && scalac -d /tmp -cp /tmp sandbox/sub.scala
==> sandbox/Test.java <==
package p1;

public class Test {
    protected Test() {}
}
==> sandbox/sub.scala <==
package p2

class C extends p1.Test()
```

Add a type parameter:
```
⚡ tail sandbox/{Test.java,sub.scala} && printf "\n" && javac -d /tmp sandbox/Test.java && scalac -d /tmp -cp /tmp sandbox/sub.scala
==> sandbox/Test.java <==
package p1;

public class Test<T> {
    protected Test() {}
}
==> sandbox/sub.scala <==
package p2

class C extends p1.Test()

sandbox/sub.scala:3: error: constructor Test in class Test cannot be accessed in package p2
 Access to protected constructor Test not permitted because
 enclosing package p2 is not a subclass of
 class Test in package p1 where target is defined
class C extends p1.Test()
                   ^
one error found
```

**Comment by lrytz** [comment] 2017-03-30 14:46
The error only shows if no type arguments are provided, i.e.,

```scala
package p2
class C extends p1.Test[String]()
```

compiles

**Comment by lrytz** [comment] 2017-03-30 14:54
Maybe caused by a cycle (just a guess, I didn't look if that's actually the order of events in the typer): to infer the type argument in the supertype (`p1.Test[Nothing]`) the typer looks at the constructor call `Test()`, which triggers accessibility checking, which looks at the incomplete supertype.

**Comment by paulp** [comment] 2017-04-02 04:41
Once known as [SI-6617](https://issues.scala-lang.org/browse/SI-6617).

**Comment by paulp** [comment] 2017-04-02 04:41
And then, in later years, as [SI-10122](https://issues.scala-lang.org/browse/SI-10122).

**Comment by SethTisue** [comment] 2019-01-09 03:16
closing as duplicate, then. scala/bug#6617, scala/bug#10122

**Closed as completed by SethTisue** 2019-01-09 03:16 UTC
