### ISSUE TITLE
ant->sbt regression: missing partest.properties in `build/pack`

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#223] opened 2016-09-12 16:11 UTC
reported by @milessabin at https://gitter.im/scala/contributors?at=57d6c250a0e8dbb04f2f86e7

the resulting misbehavior is that if you try to use sbt's `set scalaHome := Some(new java.io.File(...))` feature (either via `scalaHome` or via e.g. `++2.12.0-RC1=/Users/tisue/...` and run tests you get `java.lang.NoClassDefFoundError: org/scalatools/testing/Framework`

**Comment by SethTisue** [comment] 2016-09-12 16:13
currently the sbt build only ever writes `partest.properties` to `build/quick`, never to `build/pack`

it isn't immediately clear to me if sbt ought to write the file to `build/pack` _instead_, or it ought to write it in both places. @szeiger?

**Comment by SethTisue** [comment] 2016-09-12 16:44
hmm, maybe when running partest through sbt we should bypass `partest.properties` and just control partest's classpath directly? `test/partest` reads `build/quick/partest.properties`, but I'm tempted to suggest we ditch `test/partest` entirely and leave sbt as the only supported way of running partest? I only have light familiarity with the whole partest mess, so I'm curious what those who have more history with it think.

**Comment by szeiger** [comment] 2016-09-13 12:16
We need to write partest.properties from ant so that you can then also run it from the command line. partest.properties was deliberately moved from pack to quick because ant used to run partest on pack but sbt runs it on quick.

**Comment by szeiger** [comment] 2016-09-13 12:39
I'm not sure about setting scalaHome globally. I'll have to try that. My guess would be that it should only ever be set in bootstrap.

**Comment by SethTisue** [comment] 2016-09-13 15:51
> We need to write partest.properties from any so that you can then also run it from there command line

right, but is that even necessary to support anymore? could we make maintenance simpler by making partest available through sbt only?

**Comment by szeiger** [comment] 2016-09-15 10:55
@SethTisue That would make maintenance a bit easier but it may be an unpopular decision. I did a major cleanup of partest without Ant support here: https://github.com/scala/scala-partest/pull/68. Since running from the command line and running from sbt are pretty similar, we wouldn't gain much from removing command line support. Ant was the outlier that complicated things.

**Comment by szeiger** [comment] 2016-09-16 11:36
According to the conversation in [scala/contributors](https://gitter.im/scala/contributors?at=57d6c250a0e8dbb04f2f86e7), it seems that sbt needs partest.properties for a working scalaHome. Is this correct? I can't find any references to partest.properties in the sbt repo, and unless you published locally and ran partest you wouldn't have this file even with the ant build.

**Comment by milessabin** [comment] 2016-09-16 11:38
All I know is that seems to be a recent regression.

**Comment by szeiger** [comment] 2016-09-16 11:42
Could be a different issue. Quoting @SethTisue:

> maybe it's because in 2.12 build/pack doesn't have partest.properties with an entry for test-interface-1.0.jar

The error message indicates that it's missing ScalaTest, not test-interface, on the classpath

**Comment by milessabin** [comment] 2016-09-16 12:01
org.scalatools is owned by Lightbend ... it's nothing to do with ScalaTest.

**Comment by szeiger** [comment] 2016-09-16 12:47
Oh, yes, you're right. I thought it was org.scalatest...

**Comment by szeiger** [comment] 2016-09-19 14:07
I was able to reproduce the problem but it is not caused by the sbt build. The same problem occurs when I try to test using a local `build/pack`-style Scala created with the ant build in 2.12.0-M5.

**Comment by szeiger** [comment] 2016-09-19 14:26
Closing in favor of https://github.com/sbt/sbt/issues/2748 (this looks like an sbt bug).

**Closed as completed by szeiger** 2016-09-19 14:26 UTC
