### ISSUE TITLE
Deprecate class shadowing

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#514] opened 2018-05-15 10:33 UTC
or should this wait until 2.14? (I think I had a ticket on this already but can't find it.)

**Comment by dwijnand** [comment] 2018-05-15 11:40
What's meant by class shadowing?

**Comment by adriaanm** [comment] 2018-05-15 11:51
`class A { class C } ; class B extends A { class C } // A#C is shadowed in B`

**Comment by adriaanm** [comment] 2018-05-15 11:52
There's a ticket somewhere that shows how we get the two Cs confused. Unsoundness ensues.

**Comment by smarter** [comment] 2018-05-15 11:53
See https://github.com/lampepfl/dotty/issues/4361

**Comment by smarter** [comment] 2018-06-26 22:06
Duplicate of https://github.com/scala/scala-dev/issues/156

**Closed as completed** 2018-06-27 07:01 UTC
