### ISSUE TITLE
Java compiler crash with our library:  undeclared type variable: B1

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#159] opened 2016-06-18 13:56 UTC
```
-> scala.collection.JavaConversions$.MODULE$.collectionAsScalaIterable(Exception in thread "main" com.sun.tools.javac.code.ClassFinder$BadClassFile: bad class file: /code/scala/build/quick/classes/library/scala/collection/immutable/HashMap$$anon$2$$anon$3.class
  undeclared type variable: B1
  Please remove or make sure it appears in the correct subdirectory of the classpath.
    at com.sun.tools.javac.jvm.ClassReader.badClassFile(ClassReader.java:266)
    at com.sun.tools.javac.jvm.ClassReader.findTypeVar(ClassReader.java:856)
    at com.sun.tools.javac.jvm.ClassReader.readEnclosingMethodAttr(ClassReader.java:1194)
    at com.sun.tools.javac.jvm.ClassReader$11.read(ClassReader.java:1037)
    at com.sun.tools.javac.jvm.ClassReader.readAttrs(ClassReader.java:1280)
    at com.sun.tools.javac.jvm.ClassReader.readClassAttrs(ClassReader.java:1295)
    at com.sun.tools.javac.jvm.ClassReader.readClass(ClassReader.java:2246)
    at com.sun.tools.javac.jvm.ClassReader.readClassBuffer(ClassReader.java:2344)
    at com.sun.tools.javac.jvm.ClassReader.readClassFile(ClassReader.java:2357)
    at com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:350)
    at com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:287)
    at com.sun.tools.javac.code.ClassFinder.access$000(ClassFinder.java:74)
    at com.sun.tools.javac.code.ClassFinder$1.complete(ClassFinder.java:166)
    at com.sun.tools.javac.code.Symbol.complete(Symbol.java:590)
    at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1085)
    at com.sun.tools.javac.code.Symbol$ClassSymbol.flags(Symbol.java:1019)
    at com.sun.tools.javac.comp.Check.importAccessible(Check.java:3644)
    at com.sun.tools.javac.comp.TypeEnter$ImportsPhase.lambda$resolveImports$2(TypeEnter.java:330)
    at com.sun.tools.javac.code.Scope$FilterImportScope$SymbolImporter.lambda$importFrom$0(Scope.java:938)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
    at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
```

**Comment by dwijnand** [comment] 2020-10-22 16:00
Is that `jshell`?  I can't reproduce it:

```
$ jshell --class-path $(cs fetch -p scala)
|  Welcome to JShell -- Version 11.0.8
|  For an introduction type: /help intro

jshell> scala.collection.JavaConversions$.MODULE$.collectionAsScalaIterable(
<press tab again to see all possible completions; total possible completions: 540>

jshell> scala.collection.JavaConversions$.MODULE$.collectionAsScalaIterable(
AbstractCollection                       AbstractExecutorService                  AbstractList                             AbstractMap                              AbstractMethodError
AbstractPreferences                      AbstractQueue                            AbstractSequentialList                   AbstractSet                              AccessDeniedException
...
```

... closing.

**Closed as completed by dwijnand** 2020-10-22 16:00 UTC
Labels: prio:low
