### ISSUE TITLE
JLine 3: errors during tokenization are mishandled (in multiple ways)

### ISSUE THREAD

**Issue by Jasper-M** [scala/scala-dev#706] opened 2020-03-30 08:42 UTC
2.13.1 
```scala
scala> import scala.language.experimental.macros
import scala.language.experimental.macros

scala> import scala.reflect.macros.blackbox.Context
import scala.reflect.macros.blackbox.Context

scala> def fooMacro(c: Context): c.Tree = {import c.universe._; q"42"}
fooMacro: (c: scala.reflect.macros.whitebox.Context)c.Tree

scala> def foo: Int = macro fooMacro
defined term macro foo: Int

scala> foo
res3: Int = 42
```

2.13.2-bin-8ee21e7
```scala
scala> def foo: Int = macro fooMacro
                            ^
       error: macro implementation reference has wrong shape. required:
       macro [<static object>].<method name>[[<type args>]] or
       macro [<macro bundle>].<method name>[[<type args>]]
       note: macro definition is not supported in the REPL when using -Yrepl-classbased.
```

2.13.2-bin-bc1cad4
```scala
scala> def foo: Int = macro fooMacro                      ^
       error: macro is now a reserved word; usage as an identifier is disallowed
```

**Comment by SethTisue** [comment] 2020-04-07 01:31
marking as a blocker because I suspect the problem isn't macro-specific and there may be a whole class of errors that are mis-reported in this way

also, we'll see, but I suspect this is actually a variant of #707

**Comment by SethTisue** [comment] 2020-04-07 02:21
> I suspect the problem isn't macro-specific and there may be a whole class of errors that are mis-reported in this way

indeed,

```
scala> 0xz       ^
       error: invalid literal number
```

and note that the error is reported eagerly even in `:paste` mode:

```
scala> :paste
// Entering paste mode (ctrl-D to finish)

0xz       ^
       error: invalid literal number
```

hold your horses there Scala, wait til I hit ctrl-D to tell me I fucked up

**Comment by lrytz** [comment] 2020-04-07 07:00
> marking as a blocker

should it be on the 2.13.2 milestone?

**Comment by SethTisue** [comment] 2020-04-14 01:26
diagnosis:

in `ScalaParser#parse` (in `Reader.scala`), we have:

```
        case ACCEPT_LINE =>
          if (repl.parseString(line) == Incomplete) throw new EOFError(0, 0, "incomplete")
          tokenize(line, cursor)     // Try a real "final" parse.
```

in #707 we prevented `parseString` from printing errors, but in this case, `parseString` does not return `Incomplete`, so we go on and call `tokenize`, and that's where the error gets prematurely printed

merely wrapping the body of `tokenize` in `reporter.suppressOutput` fixes the paste-mode case (the error is suppressed, but then printed later when you exit paste mode) but then in normal mode the error never gets printed at all, so the right fix will require more finesse

**Comment by SethTisue** [comment] 2020-04-14 01:43
there are at least three different problems here:

* the missing newline in normal code
* tokenization errors aren't being suppressed during paste mode

and a third that I found just now:

* tokenization errors aren't being suppressed during tab completion either, so e.g. type `0xz` and then press the Tab key

**Comment by SethTisue** [comment] 2020-04-14 04:43
closing on the assumption https://github.com/scala/scala/pull/8880 will be merged

**Closed as completed by SethTisue** 2020-04-14 04:43 UTC
Labels: blocker, t:repl
