### ISSUE TITLE
scala build fails with None.get on compiler/compile.

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/scala-dev#399] opened 2017-06-29 10:00 UTC
around line 405 in build.sbt

```scala
Seq((dependencyClasspath in Compile).value.find(_.get(moduleID.key) == Some(asmDep)).get.data) ++
```

I have coursier enabled as a global plugin

**Comment by retronym** [comment] 2017-06-29 10:04
Hmmm, this was supposed to be fixed in https://github.com/scala/scala/pull/5399. Which branch are you using?

**Comment by MasseGuillaume** [comment] 2017-06-29 10:06
I was trying out a fix from olaf:
https://github.com/olafurpg/scala/blob/unused-terms-position-point/build.sbt#L405

**Comment by dwijnand** [comment] 2019-02-02 07:46
Closing as probably stale.  Also scala/scala#5971 mentioned this might be caused by coursier, which may also be a solved problem.

**Closed as completed by dwijnand** 2019-02-02 07:46 UTC
