### ISSUE TITLE
VerifyError when overriding a class that overrides a vararg method and makes it final

### ISSUE THREAD

**Issue by provegard** [scala/scala-dev#357] opened 2017-04-04 08:53 UTC
Consider the following three Scala source files:

JSFunction.scala:

```
import jdk.nashorn.api.scripting.AbstractJSObject

abstract class JSFunction extends AbstractJSObject {
  final override def call(thiz: scala.Any, args: AnyRef*): AnyRef = doCall(thiz, args: _*)

  def doCall(thiz: scala.Any, args: AnyRef*): AnyRef
}
```

InvokableWrapper.scala:

```
class InvokableWrapper extends JSFunction {
  override def doCall(thiz: Any, args: AnyRef*): AnyRef = {
    println("Called with: " + args.mkString(", "))
    null
  }
}
```

Main.scala:

```
object Main extends App {
  val wrapper = new InvokableWrapper
  wrapper.call(null, "a", "b")
}
```

This is what I do:

    > scalac *.scala
    > scala Main

I get:

```
java.lang.VerifyError: class InvokableWrapper overrides final method call.(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at scala.reflect.internal.util.ScalaClassLoader.run(ScalaClassLoader.scala:94)
        at scala.reflect.internal.util.ScalaClassLoader.run$(ScalaClassLoader.scala:90)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:129)
        at scala.tools.nsc.CommonRunner.run(ObjectRunner.scala:22)
        at scala.tools.nsc.CommonRunner.run$(ObjectRunner.scala:21)
        at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
        at scala.tools.nsc.CommonRunner.runAndCatch(ObjectRunner.scala:29)
        at scala.tools.nsc.CommonRunner.runAndCatch$(ObjectRunner.scala:28)
        at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:61)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:88)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:99)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:104)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```
If I remove `final` in JSFunction.scala, I get the expected output:

```
Called with: a, b
```

For reference:

    > scalac -version
    Scala code runner version 2.12.1 -- Copyright 2002-2016, LAMP/EPFL and Lightbend, Inc.

**Comment by provegard** [comment] 2017-04-04 08:58
Btw, I get this with 2.11.8 also (at least from inside IDEA with a 2.11.8 SDK).

**Comment by provegard** [comment] 2017-04-04 09:03
More information: If I put the JSFunction and InvokableWrapper classes in _the same file_, I don't get the error.

**Comment by lrytz** [comment] 2017-04-10 15:51
@provegard I cannot reproduce this issue - maybe it's the java version?

Here's what I did
```
$ java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

$ cat JSFunction.scala
import jdk.nashorn.api.scripting.AbstractJSObject

abstract class JSFunction extends AbstractJSObject {
  final override def call(thiz: scala.Any, args: AnyRef*): AnyRef = doCall(thiz, args: _*)

  def doCall(thiz: scala.Any, args: AnyRef*): AnyRef
}

$ cat InvokableWrapper.scala
class InvokableWrapper extends JSFunction {
  override def doCall(thiz: Any, args: AnyRef*): AnyRef = {
    println("Called with: " + args.mkString(", "))
    null
  }
}

$ cat Main.scala
object Main extends App {
  val wrapper = new InvokableWrapper
  wrapper.call(null, "a", "b")
}


$ rm *.class
$ scalac -version
Scala compiler version 2.12.1 -- Copyright 2002-2016, LAMP/EPFL and Lightbend, Inc.
$ scalac JSFunction.scala InvokableWrapper.scala Main.scala
$ scala Main
Called with: a, b


$ rm *.class
$ scalac11 -version
Scala compiler version 2.11.8 -- Copyright 2002-2016, LAMP/EPFL
$ scalac11 JSFunction.scala InvokableWrapper.scala Main.scala
$ scala11 Main
Called with: a, b
```

I'm closing this for here for now. Please try again and open a new issue on https://github.com/scala/bug/issues if you still manage to reproduce it.

**Closed as completed by lrytz** 2017-04-10 15:51 UTC

**Comment by provegard** [comment] 2017-04-10 18:41
Or maybe that I'm on Windows (sorry, forgot to mention that). I can reproduce with the following Java version:

```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

But you did something different than me! This works for me:

```
scalac JSFunction.scala InvokableWrapper.scala Main.scala
```

This doesn't:

```
scalac *.scala
```

**Comment by provegard** [comment] 2017-04-10 18:50
Opened [this issue](https://github.com/scala/bug/issues/10256)

**Comment by lrytz** [comment] 2017-04-10 20:30
Thanks!
