### ISSUE TITLE
j.l.String.lines (introduced JDK 11) trumps StringOps.lines

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#557] opened 2018-09-10 01:10 UTC
```
$ scala
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 11-ea).
Type in expressions for evaluation. Or try :help.

scala> "".lines.toList
<console>:12: error: value toList is not a member of java.util.stream.Stream[String]
       "".lines.toList
                ^

scala> augmentString("").lines.toList
res1: List[String] = List()

scala> ("": collection.immutable.StringOps).lines.toList
res2: List[String] = List()

scala> "".linesIterator.toList
<console>:12: warning: method linesIterator in trait StringLike is deprecated (since 2.11.0): use `lines` instead
       "".linesIterator.toList
          ^
res3: List[String] = List()
```

I propose that we undeprecate `linesIterator` in 2.12, and restore it to 2.13 (where it was already removed).

**Comment by dwijnand** [comment] 2018-09-10 01:15
Duplicate of https://github.com/scala/bug/issues/11125

**Closed as completed** 2018-09-10 01:15 UTC
Labels: task
